//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grabzujuan.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proxy
    {
        public int Id { get; set; }
        public string Ip { get; set; }
        public string Port { get; set; }
        public Nullable<System.DateTime> LastGrabTime { get; set; }
        public Nullable<System.DateTime> LastDisableTime { get; set; }
        public bool Disable { get; set; }
    }
}
