//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerXKW
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiaocaiDetail
    {
        public int Id { get; set; }
        public int JiaoCaiId { get; set; }
        public int JiaoCaiDetailId { get; set; }
        public int JiaoCaiDetailParentId { get; set; }
        public string JiaoCaiDetailName { get; set; }
        public bool IsLevel1 { get; set; }
        public bool Status { get; set; }
    }
}
