//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerXKW
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionXkw
    {
        public int Id { get; set; }
        public int QuestionId { get; set; }
        public string OriginHtml { get; set; }
        public string question_text { get; set; }
        public string source { get; set; }
        public string @class { get; set; }
        public string guid { get; set; }
        public Nullable<int> childnum { get; set; }
        public string questitle { get; set; }
        public string categories { get; set; }
        public Nullable<int> qyid { get; set; }
        public string qyname { get; set; }
        public Nullable<int> qdid { get; set; }
        public string qdname { get; set; }
        public string key { get; set; }
        public string CrawlerUrl { get; set; }
        public string QuestionAnalysis { get; set; }
        public string QuestionAnswer { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int QuestionJiaoCaiSource { get; set; }
        public string PageUrl { get; set; }
        public string SourceUrl { get; set; }
        public Nullable<int> JiaocaiId { get; set; }
        public string AnswerImg { get; set; }
        public string AnalysisImg { get; set; }
    }
}
