//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrawlerXKW
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Jiaocai
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int JiaoCaiId { get; set; }
        public string JCName { get; set; }
        public string Prefix { get; set; }
        public int DegreeId { get; set; }
        public string SubjectName { get; set; }
        public bool Status { get; set; }
        public int SubjectId { get; set; }
    }
}
